name: bb-linked-NESTED-e5e525c863bc41
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  synthetic:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "bb-linked-NESTED-e5e525c863bc41"
