name: bb-linked-NESTED-4e94910ec1a840
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  synthetic:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "bb-linked-NESTED-4e94910ec1a840"
